- name: update kernel to 3.10.0-862.14.4.el7.x86_64
  environment: "{{ proxy_env }}"
  yum: 
        name: kernel-3.10.0-862.14.4.el7.x86_64
        state: present
        disablerepo: "*"
        enablerepo: C7.5.1804-updates
