- name: copy and unpack
  unarchive: 
        src: MLNX_OFED_LINUX-4.3-3.0.2.1-rhel7.5-x86_64.tgz
        dest: /tmp

- name: build and install
  command: ./mlnxofedinstall --add-kernel-support --kmp
  args:
        chdir: /tmp/MLNX_OFED_LINUX-4.3-3.0.2.1-rhel7.5-x86_64


